language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4snapshot

services: mongodb

before_install:
  - pecl install -f mongodb
  - composer validate --strict

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit -v
