language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

services: mongodb

before_install:
  - pecl install -f mongodb

before_script:
  - composer self-update
  - composer config "platform.ext-mongo" "1.6.16"
  - composer require --no-update alcaeus/mongo-php-adapter
  - composer require --no-update doctrine/mongodb-odm "^1.3.0"
  - composer install --prefer-source
  - composer require jackalope/jackalope-doctrine-dbal doctrine/phpcr-odm

script:
  - ./vendor/bin/phpunit -v
