language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

services: mongodb

before_install:
  - pecl install -f mongodb

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit -v
